name: Corfield
favicon: null
layout_spectrum: 0.50087
typography_spectrum: 0.64094
title: Corfield
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73785932-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B8B0'
    - '#000000'
    - '#808078'
    - '#000000'
    - '#000000'
  brandStrength: 0.9939537484912314
  lightness: 0.5366355052068966
  saturation: 0.10896021281543189
  rhythmicContrast: 0.3387146991684037
purpose:
  - name: null
    item: null
    url: null
